INSERT INTO AREAS VALUES("1.01", "Direccion del Proyecto");
INSERT INTO AREAS VALUES("1.02", "Asuntos publicos");
INSERT INTO AREAS VALUES("1.03", "Legal");
INSERT INTO AREAS VALUES("1.04", "Medio ambiente");
INSERT INTO AREAS VALUES("1.05", "Geologia y recursos");
INSERT INTO AREAS VALUES("1.06", "Hidrogeologia");
INSERT INTO AREAS VALUES("1.07", "Mineria y reserva");
INSERT INTO AREAS VALUES("1.08", "Prueba de concepto D.I.S");
INSERT INTO AREAS VALUES("1.09", "Costos");
INSERT INTO AREAS VALUES("1.10", "Caso de negocio proyecto comercial");
INSERT INTO AREAS VALUES("1.11", "Control documental");

INSERT INTO subAreas values ('1.01.01', 'Inicio proyecto', '1.01');
INSERT INTO subAreas values ('1.01.02', 'Elaborar Plan de Dirección', '1.01');
INSERT INTO subAreas values ('1.01.03', 'Plan de direccion elaborado', '1.01');
INSERT INTO subAreas values ('1.01.04', 'Realizar reuniones (semanal-lunes)', '1.01');
INSERT INTO subAreas values ('1.01.05', 'Elaborar informes estado proyecto (mensual)', '1.01');
INSERT INTO subAreas values ('1.01.06', 'Realizar análisis de riesgos (plan)', '1.01');
INSERT INTO subAreas values ('1.01.07', 'Fin proyecto', '1.01');
INSERT INTO subAreas values ('1.01.08', 'Inicio proyecto - cantera', '1.01');
INSERT INTO subAreas values ('1.01.09', 'Elaborar ppta de evaluacion conceptual - Cantera', '1.01');
INSERT INTO subAreas values ('1.01.10', 'Realizar presentacion evaluacion conceptual a Directorio - Cantera', '1.01');
INSERT INTO subAreas values ('1.01.11', 'Elaborar presentacion de evaluacion de detalle - Cantera', '1.01');
INSERT INTO subAreas values ('1.01.12', 'Realizar presentacion detalle y obtener aprobacion por Directorio - Cantera', '1.01');
INSERT INTO subAreas values ('1.01.13', 'Aprobacion de evaluacion de detalle - Cantera', '1.01');
INSERT INTO subAreas values ('1.01.14', 'Realizar cierre', '1.01');
INSERT INTO subAreas values ('1.02.01', 'Realizar Levantamiento de Stakeholders', '1.02');
INSERT INTO subAreas values ('1.02.02', 'Desarrollar Plan Comunicacional', '1.02');
INSERT INTO subAreas values ('1.02.03', 'Plan Comunicación Iniciado', '1.02');
INSERT INTO subAreas values ('1.02.04', 'Elaborar página web', '1.02');
INSERT INTO subAreas values ('1.02.05', 'Recibir autorizacion preliminar hermanos Recart - Cantera', '1.02');
INSERT INTO subAreas values ('1.03.01', 'Gestionar propiedad minera (mensual)', '1.03');
INSERT INTO subAreas values ('1.03.02', 'Levantar derechos de aguas', '1.03');
INSERT INTO subAreas values ('1.03.03', 'Realizar negociaciones con dueños superficiales', '1.03');
INSERT INTO subAreas values ('1.03.04', 'Elaborar propiedad intelectual y tecnológica', '1.03');
INSERT INTO subAreas values ('1.03.05', 'Elaborar titularidad, impuesto y regalías', '1.03');
INSERT INTO subAreas values ('1.03.06', 'Elaborar marco legal (Desarrollar Alcance)', '1.03');
INSERT INTO subAreas values ('1.03.07', 'Gestionar y elaborar permisos PdC', '1.03');
INSERT INTO subAreas values ('1.04.01', 'Elaborar Línea base ambiental', '1.04');
INSERT INTO subAreas values ('1.04.02', 'Elaborar Evaluación de pertinencia ambiental', '1.04');
INSERT INTO subAreas values ('1.04.03', 'Elaborar Plan de gestión ambiental-Condiciones precedentes', '1.04');
INSERT INTO subAreas values ('1.04.04', 'Fase ejecucion - Medio Ambiente', '1.04');
INSERT INTO subAreas values ('1.04.05', 'Fase operación - Medio Ambiente', '1.04');
INSERT INTO subAreas values ('1.04.06', 'Fase cierre - Medio Ambiente', '1.04');
INSERT INTO subAreas values ('1.05.01', 'Elaborar mapa de superficie, litología y estructura', '1.05');
INSERT INTO subAreas values ('1.05.02', 'Realizar levantamiento geo-quimico de superficie XRF', '1.05');
INSERT INTO subAreas values ('1.05.03', 'Realizar muestreo de sonda sonica ICP', '1.05');
INSERT INTO subAreas values ('1.05.04', 'Realizar loggeo sondaje sónico y barreno', '1.05');
INSERT INTO subAreas values ('1.05.08', 'Determinar blanco exploratorio', '1.05');
INSERT INTO subAreas values ('1.05.09', 'Elaborar programa de sondaje sonico regional', '1.05');
INSERT INTO subAreas values ('1.05.10', 'Implementar programa sondaje sónico regional', '1.05');
INSERT INTO subAreas values ('1.05.11', 'Elaborar modelo geológico', '1.05');
INSERT INTO subAreas values ('1.05.12', 'Elaborar mapa geofísico', '1.05');
INSERT INTO subAreas values ('1.05.13', 'Elaborar modelo de recursos', '1.05');
INSERT INTO subAreas values ('1.05.14', 'Realizar estimación de recursos', '1.05');
INSERT INTO subAreas values ('1.06.01', 'Elaborar pozos de monitoreo-agua', '1.06');
INSERT INTO subAreas values ('1.06.02', 'Habilitar pozos de monitoreo', '1.06');
INSERT INTO subAreas values ('1.06.03', 'Tomar y analizar muestras- hidrogeología', '1.06');
INSERT INTO subAreas values ('1.06.04', 'Realizar preparación de probetas', '1.06');
INSERT INTO subAreas values ('1.06.05', 'Realizar pruebas de capacidad de campo', '1.06');
INSERT INTO subAreas values ('1.06.06', 'Elaborar modelo hidrogeologico', '1.06');
INSERT INTO subAreas values ('1.06.07', 'Elaborar línea base calidad agua (superficial y subterranea)', '1.06');
INSERT INTO subAreas values ('1.06.08', 'Realizar monitoreo hidrogelogico operación PdC', '1.06');
INSERT INTO subAreas values ('1.07.01', 'Diseñar métodos de extracción', '1.07');
INSERT INTO subAreas values ('1.07.02', 'Estimar Reserva', '1.07');
INSERT INTO subAreas values ('1.07.03', 'Reserva estimada', '1.07');
INSERT INTO subAreas values ('1.07.04', 'Determinar parametros geotécnicos - Cantera', '1.07');
INSERT INTO subAreas values ('1.07.05', 'Elaborar diseño de mina y programa de producción - Cantera', '1.07');
INSERT INTO subAreas values ('1.07.06', 'Determinar OPEX y CAPEX mina - Cantera', '1.07');
INSERT INTO subAreas values ('1.08.01', 'Metalurgia (under ground/ above ground)', '1.08');
INSERT INTO subAreas values ('1.08.02', 'Procesamiento Mineral - Cantera', '1.08');
INSERT INTO subAreas values ('1.08.03', 'Realizar configuración del diseño PdC in-situ', '1.08');
INSERT INTO subAreas values ('1.08.04', 'Desarrolar la Ingeniería', '1.08');
INSERT INTO subAreas values ('1.08.05', 'Diseñar plan de cierre PdC', '1.08');
INSERT INTO subAreas values ('1.08.06', 'Elaborar plan de control y monitoreo de emisiones PdC', '1.08');
INSERT INTO subAreas values ('1.08.07', 'Elaborar plan de secuencia y programación de producción PdC', '1.08');
INSERT INTO subAreas values ('1.08.08', 'Infraestructura Off-site - PdC', '1.08');
INSERT INTO subAreas values ('1.08.09', 'Infraestructura On-site - PdC ****', '1.08');
INSERT INTO subAreas values ('1.08.10', 'Contratar e implementar servicios - Cantera', '1.08');
INSERT INTO subAreas values ('1.08.11', 'Construir planta - Cantera', '1.08');
INSERT INTO subAreas values ('1.08.12', 'Infraestructura Underground - PdC', '1.08');
INSERT INTO subAreas values ('1.08.13', 'Infraestructura Above ground', '1.08');
INSERT INTO subAreas values ('1.08.14', 'Planta PdC', '1.08');
INSERT INTO subAreas values ('1.08.15', 'Definir la organización- PdC', '1.08');
INSERT INTO subAreas values ('1.08.16', 'Operación PdC in-situ', '1.08');
INSERT INTO subAreas values ('1.08.17', 'Operación faena cantera', '1.08');
INSERT INTO subAreas values ('1.08.18', 'Ejecutar plan de cierre PdC', '1.08');
INSERT INTO subAreas values ('1.08.19', 'Gestionar HSEC- PdC', '1.08');
INSERT INTO subAreas values ('1.08.20', 'Gestionar Calidad- PdC', '1.08');
INSERT INTO subAreas values ('1.08.21', 'Determinar OPEX y CAPEX- PdC', '1.08');
INSERT INTO subAreas values ('1.09.01', 'Estimar costos de inversión', '1.09');
INSERT INTO subAreas values ('1.09.02', 'Estimar costos de operación', '1.09');
INSERT INTO subAreas values ('1.10.01', 'Contactar joint venture', '1.10');
INSERT INTO subAreas values ('1.10.02', 'Desarrollar la Ingenieria Conceptual proyecto comercial', '1.10');
INSERT INTO subAreas values ('1.10.03', 'Ingenieria Conceptual proyecto comercial iniciado', '1.10');
INSERT INTO subAreas values ('1.10.04', 'Elaborar informe de marketing', '1.10');
INSERT INTO subAreas values ('1.10.05', 'Realizar la evaluación económica del proyecto', '1.10');
INSERT INTO subAreas values ('1.10.06', 'Elaborar caso negocio', '1.10');
INSERT INTO subAreas values ('1.10.07', 'Presentar y recibir la aprobación del Caso Negocio', '1.10');
INSERT INTO subAreas values ('1.10.08', 'Caso de negocio aprobado', '1.10');
INSERT INTO subAreas values ('1.10.09', 'Desarrollar evaluación economica conceptual - Cantera', '1.10');
INSERT INTO subAreas values ('1.10.10', 'Determinar eventuales Clientes y acordar termino de comercialización', '1.10');
INSERT INTO subAreas values ('1.10.11', 'Realizar la evaluación económica de detalle del proyecto - Cantera', '1.10');
INSERT INTO subAreas values ('1.11.01', 'Implementar sistema control documental', '1.11');
INSERT INTO subAreas values ('1.11.02', 'Elaborar listado Documentos técnicos', '1.11');
INSERT INTO subAreas values ('1.11.03', 'Elaborar listado Planos', '1.11');
INSERT INTO subAreas values ('1.11.04', 'Elaborar listado Documentos especiales', '1.11');


INSERT INTO gruposDisciplina values (1, 'Geologia');
INSERT INTO gruposDisciplina values (2, 'Hidrogeologia');
INSERT INTO gruposDisciplina values (3, 'Minería');
INSERT INTO gruposDisciplina values (4, 'Metalurgia');
INSERT INTO gruposDisciplina values (5, 'Aboveground');
INSERT INTO gruposDisciplina values (6, 'Operación');
INSERT INTO gruposDisciplina values (7, 'Administración');
INSERT INTO gruposDisciplina values (8, 'Direccion y Control');
INSERT INTO gruposDisciplina values (9, 'General');

INSERT INTO disciplinas values ('10', 'Sondaje', 1);
INSERT INTO disciplinas values ('11', 'Geoquímica', 1);
INSERT INTO disciplinas values ('12', 'Geología', 1);
INSERT INTO disciplinas values ('13', 'Geofísica', 1);
INSERT INTO disciplinas values ('14', 'Sistema de información Geografica', 1);
INSERT INTO disciplinas values ('15', 'Estimacion de recursos', 1);
INSERT INTO disciplinas values ('21', 'Hidrogeologia', 2);
INSERT INTO disciplinas values ('31', 'Perforacion', 3);
INSERT INTO disciplinas values ('32', 'Plan Minero Desorción In-situ', 3);
INSERT INTO disciplinas values ('33', 'Estimacion de reservas', 3);
INSERT INTO disciplinas values ('34', 'Evaluacion economica', 3);
INSERT INTO disciplinas values ('41', 'Desorcion', 4);
INSERT INTO disciplinas values ('42', 'Precipitacion', 4);
INSERT INTO disciplinas values ('43', 'Separacion solido -liquido', 4);
INSERT INTO disciplinas values ('44', 'Calcinacion', 4);
INSERT INTO disciplinas values ('45', 'Manejo de Residuos (RISES Y RILES)', 4);
INSERT INTO disciplinas values ('50', 'Arquitectura', 5);
INSERT INTO disciplinas values ('51', 'Servicio de Construccion', 5);
INSERT INTO disciplinas values ('52', 'Civil', 5);
INSERT INTO disciplinas values ('53', 'Comunicaciones', 5);
INSERT INTO disciplinas values ('54', 'Concreto', 5);
INSERT INTO disciplinas values ('55', 'Sistema de control', 5);
INSERT INTO disciplinas values ('56', 'Eléctrico', 5);
INSERT INTO disciplinas values ('57', 'Estudios de Electrificación', 5);
INSERT INTO disciplinas values ('58', 'Gestión de Ingeniería', 5);
INSERT INTO disciplinas values ('59', 'Geotécnica', 5);
INSERT INTO disciplinas values ('5A', 'Instrumentación', 5);
INSERT INTO disciplinas values ('5B', 'Layout', 5);
INSERT INTO disciplinas values ('5C', 'Mecánica', 5);
INSERT INTO disciplinas values ('5D', 'Piping', 5);
INSERT INTO disciplinas values ('5E', 'Procesos', 5);
INSERT INTO disciplinas values ('5F', 'Estructural', 5);
INSERT INTO disciplinas values ('5G', 'Transporte', 5);
INSERT INTO disciplinas values ('61', 'Operación', 6);
INSERT INTO disciplinas values ('62', 'Entrenamiento', 6);
INSERT INTO disciplinas values ('70', 'Contabilidad', 7);
INSERT INTO disciplinas values ('71', 'Administración', 7);
INSERT INTO disciplinas values ('72', 'Finanzas', 7);
INSERT INTO disciplinas values ('73', 'Recursos Humanos', 7);
INSERT INTO disciplinas values ('74', 'Logística', 7);
INSERT INTO disciplinas values ('75', 'Comercialización', 7);
INSERT INTO disciplinas values ('76', 'Evaluación de proyectos', 7);
INSERT INTO disciplinas values ('77', 'Publicidad', 7);
INSERT INTO disciplinas values ('80', 'Control de Proyecto', 8);
INSERT INTO disciplinas values ('81', 'Control de documentos', 8);
INSERT INTO disciplinas values ('82', 'Gestión', 8);
INSERT INTO disciplinas values ('83', 'Planificación de proyecto', 8);
INSERT INTO disciplinas values ('90', 'Relaciones públicas', 9);
INSERT INTO disciplinas values ('91', 'Corporativo', 9);
INSERT INTO disciplinas values ('92', 'Ambiental', 9);
INSERT INTO disciplinas values ('93', 'Salud y seguridad.', 9);
INSERT INTO disciplinas values ('94', 'Sistema Integrado de Gestión', 9);
INSERT INTO disciplinas values ('95', 'Legal.', 9);
INSERT INTO disciplinas values ('96', 'Calidad', 9);


INSERT INTO gruposTipoDocumento VALUES ('A', 'Requerimiento');
INSERT INTO gruposTipoDocumento VALUES ('B', 'Dibujo/Plano');
INSERT INTO gruposTipoDocumento VALUES ('C', 'Especificacion');
INSERT INTO gruposTipoDocumento VALUES ('D', 'Diseño');
INSERT INTO gruposTipoDocumento VALUES ('E', 'Licitacion');
INSERT INTO gruposTipoDocumento VALUES ('F', 'Administracion del Contrato');
INSERT INTO gruposTipoDocumento VALUES ('G', 'Comunicación');
INSERT INTO gruposTipoDocumento VALUES ('H', 'Formato');
INSERT INTO gruposTipoDocumento VALUES ('I', 'Entregable');
INSERT INTO gruposTipoDocumento VALUES ('J', 'Pagos');

INSERT INTO tiposDocumento values ('AA', 'Ingeniería / Requisiciones técnicas', 'A');
INSERT INTO tiposDocumento values ('AB', 'Solicitud de orden de cambio', 'A');
INSERT INTO tiposDocumento values ('AC', 'Requerimiento de información', 'A');
INSERT INTO tiposDocumento values ('AD', 'Orden de trabajo', 'A');
INSERT INTO tiposDocumento values ('AE', 'Orden de compra', 'A');
INSERT INTO tiposDocumento values ('BA', 'Planos de proceso', 'B');
INSERT INTO tiposDocumento values ('BB', 'Planos de distribución / ubicación', 'B');
INSERT INTO tiposDocumento values ('BC', 'Plano topográfico', 'B');
INSERT INTO tiposDocumento values ('BD', 'Mapa/Secciones', 'B');
INSERT INTO tiposDocumento values ('BE', 'Planos de fabricación / construcción', 'B');
INSERT INTO tiposDocumento values ('BF', 'Esquema preliminar', 'B');
INSERT INTO tiposDocumento values ('CA', 'Especificaciones de Construcción', 'C');
INSERT INTO tiposDocumento values ('CB', 'Especificaciones de instalación', 'C');
INSERT INTO tiposDocumento values ('CC', 'Especificaciones de Materiales/Equipos', 'C');
INSERT INTO tiposDocumento values ('CD', 'Especificaciones estándar', 'C');
INSERT INTO tiposDocumento values ('CE', 'Especificaciones técnicas', 'C');
INSERT INTO tiposDocumento values ('DA', 'Parametros de diseño', 'D');
INSERT INTO tiposDocumento values ('DB', 'Cálculos de diseño', 'D');
INSERT INTO tiposDocumento values ('DC', 'Criterios de diseño', 'D');
INSERT INTO tiposDocumento values ('EA', 'Especificacion oferta administrativa', 'E');
INSERT INTO tiposDocumento values ('EB', 'Especificacion oferta general', 'E');
INSERT INTO tiposDocumento values ('EC', 'Especificacion oferta técnica', 'E');
INSERT INTO tiposDocumento values ('ED', 'Evaluacion economica de la oferta', 'E');
INSERT INTO tiposDocumento values ('EE', 'Documento Maestro del Alcance', 'E');
INSERT INTO tiposDocumento values ('EF', 'Evaluacion técnica de la oferta', 'E');
INSERT INTO tiposDocumento values ('FA', 'Carta adjudicacion', 'F');
INSERT INTO tiposDocumento values ('FB', 'Contrato', 'F');
INSERT INTO tiposDocumento values ('FC', 'Estado de pago', 'F');
INSERT INTO tiposDocumento values ('FD', 'Finquito contrato', 'F');
INSERT INTO tiposDocumento values ('GA', 'Audio', 'G');
INSERT INTO tiposDocumento values ('GB', 'Correo Electrónico', 'G');
INSERT INTO tiposDocumento values ('GC', 'Carta', 'G');
INSERT INTO tiposDocumento values ('GD', 'Respaldo de correspondencia', 'G');
INSERT INTO tiposDocumento values ('GE', 'Memorándum', 'G');
INSERT INTO tiposDocumento values ('GF', 'Minutas', 'G');
INSERT INTO tiposDocumento values ('GG', 'Fotos', 'G');
INSERT INTO tiposDocumento values ('GH', 'Presentaciones', 'G');
INSERT INTO tiposDocumento values ('GI', 'Videos', 'G');
INSERT INTO tiposDocumento values ('HA', 'Formulario', 'F');
INSERT INTO tiposDocumento values ('HB', 'Instructivo', 'F');
INSERT INTO tiposDocumento values ('HC', 'Manuales', 'F');
INSERT INTO tiposDocumento values ('HD', 'Procedimientos', 'F');
INSERT INTO tiposDocumento values ('HE', 'Registros', 'F');
INSERT INTO tiposDocumento values ('IA', 'Informe Flash de Accidentes', 'I');
INSERT INTO tiposDocumento values ('IB', 'Informe de Accidente / Informe de Incidente', 'I');
INSERT INTO tiposDocumento values ('IC', 'Informe administrativo', 'I');
INSERT INTO tiposDocumento values ('ID', 'Lista de chequeo', 'I');
INSERT INTO tiposDocumento values ('IE', 'Informe de control', 'I');
INSERT INTO tiposDocumento values ('IF', 'Informe económico', 'I');
INSERT INTO tiposDocumento values ('IG', 'Lista', 'I');
INSERT INTO tiposDocumento values ('IH', 'Informe de avance', 'I');
INSERT INTO tiposDocumento values ('II', 'Estudio', 'I');
INSERT INTO tiposDocumento values ('IJ', 'Programa', 'I');
INSERT INTO tiposDocumento values ('IK', 'Informe técnico', 'I');
INSERT INTO tiposDocumento values ('IL', 'Data Sheet', 'I');
INSERT INTO tiposDocumento values ('JA', 'Boleta', 'J');
INSERT INTO tiposDocumento values ('JB', 'Factura', 'J');
INSERT INTO tiposDocumento values ('JC', 'Reembolso', 'J');


INSERT INTO versiones values ('V0A', 'INTERNA');
INSERT INTO versiones values ('V0B', 'CLIENTE/ REVISOR');
INSERT INTO versiones values ('V00', 'VERSION APROBADA');

INSERT INTO usuarios values (null, 'admin', 'administrador', '', '', '123', 1, 1, 1, 1);

-- ESTOS INSERTS DE AQUI PARA ABAJO SON SOLO DE PRUEBA (NO VAN EN LA APLICACION UNA VEZ PUBLICADA)
INSERT INTO gruposUsuario values (null, 'Gerentes');
INSERT INTO gruposUsuario values (null, 'Administrativos');
INSERT INTO gruposUsuario values (null, 'Ejecutivos');
INSERT INTO gruposUsuario values (null, 'Contratistas');

INSERT INTO usuarios values (null, 'fco001', 'francisco', 'martinez', 'fco_martines@hotmail.com', '123', 1, 1, 1, 1);
INSERT INTO usuarios values (null, 'erwin001', 'erwin', 'troncoso', 'erwin@hotmail.com', '123', 1, 1, 1, 1);
INSERT INTO usuarios values (null, 'alcaro001', 'alvaro', 'troncoso', 'troncoso23@hotmail.com', '123', 0, 1, 0, 1);
INSERT INTO usuarios values (null, 'martin001', 'martin', 'rivas', 'martin_rivas@hotmail.com', '123', 0, 1, 0, 1);
INSERT INTO usuarios values (null, 'carlos001', 'carlos', 'carmona', 'carlos@hotmail.com', '123', 1, 0, 0, 1);
INSERT INTO usuarios values (null, 'lidia001', 'lidia', 'manrriquez', 'manrriquez069@hotmail.com', '123', 0, 1, 0, 1);
INSERT INTO usuarios values (null, 'marin001', 'marin', 'estuardo', 'marin.elpelao@hotmail.com', '123', 0, 1, 1, 1);
INSERT INTO usuarios values (null, 'pata001', 'patricia', 'sobarzo', 'pata_sobarzo@hotmail.com', '123', 0, 0, 1, 1);
INSERT INTO usuarios values (null, 'myriam001', 'myriam', 'godoy', 'myriam@hotmail.com', '123', 1, 1, 1, 0);
INSERT INTO usuarios values (null, 'susan001', 'susana', 'lopez', 'susi.lopez@hotmail.com', '123', 1, 1, 1, 0);
INSERT INTO usuarios values (null, 'nico001', 'nicolas', 'hidalgo', 'don.hidalgo@hotmail.com', '123', 1, 1, 1, 0);
INSERT INTO usuarios values (null, 'fko001', 'francisco', 'quiñones', 'fco_el_loco@hotmail.com', '123', 1, 1, 1, 0);

INSERT INTO grupoUsuarioUsuario values (1, 1);
INSERT INTO grupoUsuarioUsuario values (1, 2);
INSERT INTO grupoUsuarioUsuario values (1, 3);
INSERT INTO grupoUsuarioUsuario values (2, 4);
INSERT INTO grupoUsuarioUsuario values (2, 5);
INSERT INTO grupoUsuarioUsuario values (3, 6);

INSERT INTO logsUsuarios values (null, 1, 'Inicio sesion', CURRENT_TIMESTAMP);

INSERT INTO sesionesUsuariosPorID values (null, 1, '542c8686d5184', 1);

INSERT INTO correlativodisciplina (`correlativo`, `codDisciplina`) VALUES ('1', '43');

